Traceback (most recent call last):
  File "c:\users\kirim\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kirim\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kirim\AppData\Local\Programs\Python\Python37-32\Scripts\sphinx-build.exe\__main__.py", line 7, in <module>
  File "c:\users\kirim\appdata\local\programs\python\python37-32\lib\site-packages\sphinx\cmd\build.py", line 288, in main
    return make_main(argv)
  File "c:\users\kirim\appdata\local\programs\python\python37-32\lib\site-packages\sphinx\cmd\build.py", line 195, in make_main
    return make_mode.run_make_mode(argv[1:])
  File "c:\users\kirim\appdata\local\programs\python\python37-32\lib\site-packages\sphinx\cmd\make_mode.py", line 166, in run_make_mode
    return getattr(make, run_method)()
  File "c:\users\kirim\appdata\local\programs\python\python37-32\lib\site-packages\sphinx\cmd\make_mode.py", line 83, in build_clean
    rmtree(self.builddir_join(item))
  File "c:\users\kirim\appdata\local\programs\python\python37-32\lib\site-packages\sphinx\util\osutil.py", line 275, in rmtree
    shutil.rmtree(path)
  File "c:\users\kirim\appdata\local\programs\python\python37-32\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\kirim\appdata\local\programs\python\python37-32\lib\shutil.py", line 404, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "c:\users\kirim\appdata\local\programs\python\python37-32\lib\shutil.py", line 402, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'build\\latex'
Removing everything under 'build'...
